STRINGS=GLOBAL.STRINGS
STRINGS.UI.DREAMLOAD={}
STRINGS.UI.DREAMLOAD.BODY =[[Do you went to the dream?]]
STRINGS.UI.DREAMLOAD.TITLE=[[Go to the dream]]
STRINGS.UI.DREAMLOAD.YES=[[I WANT]]
STRINGS.UI.DREAMLOAD.NO=[[NO!!]]
